---
- id: detekt
  name: Detekt
  description: "Runs the Detekt static code analyzer on Kotlin source files."
  language: coursier
  entry: detekt
  pass_filenames: false
  files: \.kt$
  require_serial: true
- id: ktlint
  name: ktlint
  description: "Runs the ktlint linter and formatter on Kotlin source files."
  language: coursier
  entry: ktlint
  files: \.kt$
  require_serial: true
